### ISSUE TITLE
想问个和本repo无关的问题。。。

### ISSUE THREAD

**Issue by ice1000** [Kiritow/SimpleSDLGame#1]
我想拿SDL写点东西，需要怎么配置环境啊（初学编程时尝试配环境结果搞了十几个小时也没搞好） :cry:

**Comment by Kiritow** [comment]
喵喵喵？我是在CodeBlock下编写和运行SDL代码的，我从官网上下载的SDL2-devel-2.0.4-mingw.tar.gz这个文件然后把里面的文件夹直接和codeblocks的bin、include和lib合并，编译的时候加上-lSDL2 -lSDL2main -lSDL2test就可以了。如果说找不到main函数的话就在包含SDL.h之后加上#undef main

**Comment by Kiritow** [comment]
我之前的一篇博客QwQ [View On CSDN](http://blog.csdn.net/kiritow/article/details/50451793)

**Comment by ice1000** [comment]
嗷嗷嗷感谢，回家试试Orz

**Comment by ice1000** [comment]
送上一颗星星以示谢意~ :joy:

**Comment by Kiritow** [comment]
谢谢~

**Comment by ice1000** [comment]
回复这么快，吓得我还以为邮箱bug了Orz（翘课出来的Orz）

**Comment by Kiritow** [comment]
因为我正在GitHub上溜达呢😂
